version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      # DATABASE_URL punta al file SQLite
      DATABASE_URL: "file:./dev.db"
      NODE_ENV: production
      # Google OAuth (da .env)
      GOOGLE_CLIENT_ID: "736808508716-v8fsr1rto12qjg8pnqtecs2qrpvdqs74.apps.googleusercontent.com"
      GOOGLE_CLIENT_SECRET: "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"
      GOOGLE_REDIRECT_URI: "https://localhost:5000/auth/google/callback"
      # SSL opzionale
      HTTPS: ""
    ports:
      - "5000:5000"
    volumes:
      # Cartella per il database SQLite (persistente)
      - ./prisma:/app/prisma
      # Cartelle per upload e certificati
      - ./uploads:/app/uploads
      - ./certs:/app/certs
      # File .env
      - ./.env:/app/.env
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "80:80"
