FROM node:20-alpine

WORKDIR /app

# Copio solo i manifest per sfruttare la cache
COPY package*.json ./
RUN npm install

# Copio il resto del progetto
COPY . .

# Vite usa 5173
EXPOSE 5173

# Avvio del server dev accessibile dall'esterno
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
